"""Core foundation modules for xnatio.

This package contains the fundamental building blocks:
- exceptions: Custom exception hierarchy for precise error handling
- validation: Input validation for URLs, ports, identifiers, paths
- logging: Structured logging with correlation IDs and audit support
- utils: Utility functions for archive handling
"""

from .exceptions import (
    XNATError,
    ConfigurationError,
    MissingCredentialsError,
    InvalidConfigurationError,
    ConnectionError,
    AuthenticationError,
    ServerUnreachableError,
    SessionExpiredError,
    ValidationError,
    InvalidIdentifierError,
    InvalidURLError,
    InvalidPortError,
    PathValidationError,
    ResourceError,
    ResourceNotFoundError,
    ResourceExistsError,
    ResourceAccessDeniedError,
    UploadError,
    DicomUploadError,
    ArchiveUploadError,
    ResourceUploadError,
    DownloadError,
    SessionDownloadError,
    OperationError,
    BatchOperationError,
    CatalogRefreshError,
    RenameError,
    DeleteError,
    NetworkError,
    TimeoutError,
    RetryExhaustedError,
    DicomError,
    DicomParseError,
    DicomStoreError,
)

from .logging import (
    setup_logging,
    get_logger,
    get_audit_logger,
    LogContext,
    log_operation,
    get_correlation_id,
    set_correlation_id,
    generate_correlation_id,
    clear_correlation_id,
    mask_sensitive,
    sanitize_for_log,
    AuditLogger,
    StandardFormatter,
    JSONFormatter,
)

from .validation import (
    validate_server_url,
    validate_url_or_none,
    validate_port,
    validate_xnat_identifier,
    validate_project_id,
    validate_subject_id,
    validate_session_id,
    validate_scan_id,
    validate_resource_label,
    validate_ae_title,
    validate_path_exists,
    validate_path_writable,
    validate_archive_path,
    validate_dicom_directory,
    validate_timeout,
    validate_workers,
    validate_overwrite_mode,
    validate_scan_ids_input,
    validate_project_list,
    validate_regex_pattern,
)

from .utils import (
    is_allowed_archive,
    zip_dir_to_temp,
)

__all__ = [
    # Exceptions
    "XNATError",
    "ConfigurationError",
    "MissingCredentialsError",
    "InvalidConfigurationError",
    "ConnectionError",
    "AuthenticationError",
    "ServerUnreachableError",
    "SessionExpiredError",
    "ValidationError",
    "InvalidIdentifierError",
    "InvalidURLError",
    "InvalidPortError",
    "PathValidationError",
    "ResourceError",
    "ResourceNotFoundError",
    "ResourceExistsError",
    "ResourceAccessDeniedError",
    "UploadError",
    "DicomUploadError",
    "ArchiveUploadError",
    "ResourceUploadError",
    "DownloadError",
    "SessionDownloadError",
    "OperationError",
    "BatchOperationError",
    "CatalogRefreshError",
    "RenameError",
    "DeleteError",
    "NetworkError",
    "TimeoutError",
    "RetryExhaustedError",
    "DicomError",
    "DicomParseError",
    "DicomStoreError",
    # Logging
    "setup_logging",
    "get_logger",
    "get_audit_logger",
    "LogContext",
    "log_operation",
    "get_correlation_id",
    "set_correlation_id",
    "generate_correlation_id",
    "clear_correlation_id",
    "mask_sensitive",
    "sanitize_for_log",
    "AuditLogger",
    "StandardFormatter",
    "JSONFormatter",
    # Validation
    "validate_server_url",
    "validate_url_or_none",
    "validate_port",
    "validate_xnat_identifier",
    "validate_project_id",
    "validate_subject_id",
    "validate_session_id",
    "validate_scan_id",
    "validate_resource_label",
    "validate_ae_title",
    "validate_path_exists",
    "validate_path_writable",
    "validate_archive_path",
    "validate_dicom_directory",
    "validate_timeout",
    "validate_workers",
    "validate_overwrite_mode",
    "validate_scan_ids_input",
    "validate_project_list",
    "validate_regex_pattern",
    # Utils
    "is_allowed_archive",
    "zip_dir_to_temp",
]
