"""Shared defaults for uploader modules and CLI options."""

DEFAULT_NUM_BATCHES = 42
DEFAULT_UPLOAD_WORKERS = 42
DEFAULT_ARCHIVE_WORKERS = 5
DEFAULT_ARCHIVE_FORMAT = "tar"
DEFAULT_TIMEOUT = 10800
DEFAULT_IMPORT_HANDLER = "DICOM-zip"
DEFAULT_OVERWRITE = "delete"

DEFAULT_DICOM_STORE_BATCHES = 45
DEFAULT_DICOM_CALLING_AET = "XNATIO"
